version: '3'

services:
  backend:
    container_name: "nest_api"
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
